
import Project.Conn;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author Administrator
 */
public class Getticket extends javax.swing.JInternalFrame {

    /**
     * Creates new form Getticket
     */
    public Getticket() {
        initComponents();
        this.setSize(530,270+22);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        departure = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        flightid = new javax.swing.JLabel();
        firstname = new javax.swing.JLabel();
        contact = new javax.swing.JLabel();
        lastname = new javax.swing.JLabel();
        arrival = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ticketid = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Thanks for choosing Bleu Ciel Airlines");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel3.setText("First Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 50, -1, -1));

        jLabel4.setText("Last Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 79, -1, -1));

        jLabel5.setText("Gender");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 108, -1, -1));

        jLabel6.setText("Arrival");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        jLabel7.setText("Departure");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, -1));

        jLabel8.setText("Contact");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, -1, -1));

        jLabel9.setText("Flight id");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));
        jPanel1.add(departure, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 60, 20));
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 50, 20));
        jPanel1.add(flightid, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 50, 20));
        jPanel1.add(firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 50, 20));
        jPanel1.add(contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 60, 20));
        jPanel1.add(lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 50, 20));
        jPanel1.add(arrival, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 60, 20));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Downloads\\download (21).jpg")); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, -140, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 430, 150));

        jLabel1.setText("Ticket ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 13, 53, 24));
        getContentPane().add(ticketid, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 14, 69, -1));

        jButton1.setText("Get Ticket");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 13, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Downloads\\download (21).jpg")); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, -120, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     // TODO add your handling code here:
String Ticket = ticketid.getText();

try {
    Connection con = Conn.getCon();
    PreparedStatement pre;

    // Join Ticket, Passenger, and Flight tables to get the required details
    pre = con.prepareStatement("SELECT p.Firstname, p.Lastname, p.Gender, p.Contact, "
                                + "f.Flightid, f.Arrival, f.Departure "
                                + "FROM Ticket t "
                                + "JOIN Passenger p ON t.Passengerid = p.Passengerid "
                                + "JOIN Flight f ON t.Flightid = f.Flightid "
                                + "WHERE t.Ticketid = ?");
    pre.setString(1, Ticket);

    ResultSet rs = pre.executeQuery();

    if (rs.next()) {
        firstname.setText(rs.getString("Firstname"));
        lastname.setText(rs.getString("Lastname"));
        gender.setText(rs.getString("Gender"));
        flightid.setText(rs.getString("Flightid"));
        arrival.setText(rs.getString("Arrival"));
        departure.setText(rs.getString("Departure"));
        contact.setText(rs.getString("Contact"));
    }

            else
            {
                JOptionPane.showMessageDialog(null,"Ticket does not exist");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Searchpassenger.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arrival;
    private javax.swing.JLabel contact;
    private javax.swing.JLabel departure;
    private javax.swing.JLabel firstname;
    private javax.swing.JLabel flightid;
    private javax.swing.JLabel gender;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lastname;
    private javax.swing.JTextField ticketid;
    // End of variables declaration//GEN-END:variables
}
